---
version: '3'

services:
  bot:
    build: .
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    stdin_open: true
    tty: true
    env_file: .env
    restart: always
